(function(){
    window.onload = function(){
        var builder = new FDOMBuilder();
        builder
            .child("form")
                .action("/")
                .method("get")
                .child("div")
                    .text("What is your name?")
                .endChild()
                .child("input")
                    .type("text")
                    .name("name")
                .endChild()
                .child("div")
                    .text("Select a image:")
                .endChild()
                .child("input")
                    .type("radio")
                    .name("image")
                    .value("github")
                .endChild()
                .child("a")
                    .href("http://www.github.com/haritzmedina")
                    .target("_blank")
                    .child("img")
                        .src("https://cdn0.iconfinder.com/data/icons/octicons/1024/mark-github-128.png")
                    .endChild()
                .endChild()
                .child("input")
                    .type("radio")
                    .name("image")
                    .value("bitbucket")
                .endChild()
                .child("a")
                    .href("https://bitbucket.org/haritzmedina/")
                    .target("_blank")
                    .child("img")
                        .src("https://cdn2.iconfinder.com/data/icons/designer-skills/128/bitbucket-repository-svn-manage-files-contribute-branch-128.png")
                        .css("width", "200px")
                    .endChild()
                .endChild()
                .child("div")
                .endChild()
                .child("input")
                    .type("submit")
                    .value("Send")
                .endChild()
            .endChild();
    };
})();